dht 1.0 updates
degauss-org/roads pull request #4
Opened 2022-02-17 19:21 UTC by erikarasnick

2022-02-17 23:13 UTC, erikarasnick commented
I think this has everything except the citation file.

2022-02-18 19:42 UTC, cole-brokamp requested changes

2022-02-18 19:42 UTC, cole-brokamp commented on entrypoint.R
> +           l = map_dbl(road_index, length),
this works if there is more than one road segment that a buffer intersects with, right?

2022-02-18 19:42 UTC, cole-brokamp commented on LICENSE.md
> +GNU General Public License
I updated {dht}  (again...) to have `LICENSE` instead of `LICENSE.md`, which looks better on github.  Here, we can delete the older `LICENSE` and rename this `LICENSE.md` to `LICENSE`

2022-02-18 19:46 UTC, cole-brokamp requested changes

2022-02-18 19:46 UTC, cole-brokamp commented on entrypoint.R
> +
also, can we add a `dht::check_ram(4)` here?  (assuming that 4 GB should still be necessary, right?)

2022-02-22 15:25 UTC, erikarasnick commented on entrypoint.R
> +           l = map_dbl(road_index, length),
yes, I manually confirmed, and I added another line to the test file that overlaps more roads as well as another test to the makefile to use a 1000 m buffer.

2022-02-22 16:03 UTC, cole-brokamp approved these changes
thanks!  have you tried to run old and new and see what the speed up is?

2022-02-22 16:17 UTC, erikarasnick commented
For the 5 rows in the test file that do not have missing lat/lon, the old version took about 42 seconds, and the new version took about 35 seconds... some improvement that would hopefully scale well for a larger dataset.

2022-02-22 16:17 UTC, merged